
print("hello Greg...welcome to R")

library('ggplot2')
data = read.table('C:/Users/gabsbi/Desktop/MyRscript/REDUCE_CLASSIFYdatasets/iris_tab.txt', header = TRUE)
Sp = data$species; # species
SL = data$sepal_length; # sepal length
SW = data$sepal_width; # sepal width
PL = data$petal_length; # petal length
PW = data$petal_width; # petal width
dataframe = data.frame(SL, SW, PL, PW, Sp)
print (dataframe)
myplot1 <- ggplot(data = dataframe, mapping = aes(x = Sp, y = SL)) + geom_boxplot() + labs(x = 'species', y = 'Sepal Length') + theme(axis.text.x=element_text(angle=15), panel.background = element_rect(fill = 'grey50'))
myplot2 <- ggplot(data = dataframe, mapping = aes(x = Sp, y = SW)) + geom_boxplot() + labs(x = 'species', y = 'Sepal Width') + theme(axis.text.x=element_text(angle=15), panel.background = element_rect(fill = 'grey50'))
myplot3 <- ggplot(data = dataframe, mapping = aes(x = Sp, y = PL)) + geom_boxplot() + labs(x = 'species', y = 'Petal Length') + theme(axis.text.x=element_text(angle=15), panel.background = element_rect(fill = 'grey50'))
myplot4 <- ggplot(data = dataframe, mapping = aes(x = Sp, y = PW)) + geom_boxplot() + labs(x = 'species', y = 'Petal Width') + theme(axis.text.x=element_text(angle=15), panel.background = element_rect(fill = 'grey50'))
mytest1 <- oneway.test(SL~Sp)
mytest2 <- oneway.test(SW~Sp)
mytest3 <- oneway.test(PL~Sp)
mytest4 <- oneway.test(PW~Sp)
Y <- cbind(SL,SW,PL,PW)
print (Y)
mytest5 <- manova(Y~Sp, data = dataframe)
print (mytest1)
print (mytest2)
print (mytest3)
print (mytest4)
myMANOVA <- summary(mytest5, test="Pillai")
print(myMANOVA)
library('grid')
pushViewport(viewport(layout = grid.layout(2, 2)))
print(myplot1, vp = viewport(layout.pos.row = 1, layout.pos.col = 1))
print(myplot2, vp = viewport(layout.pos.row = 1, layout.pos.col = 2))
print(myplot3, vp = viewport(layout.pos.row = 2, layout.pos.col = 1))
print(myplot4, vp = viewport(layout.pos.row = 2, layout.pos.col = 2))
sink("statsMANOVA.txt")
print (mytest1)
print (mytest2)
print (mytest3)
print (mytest4)
myMANOVA <- summary(mytest5, test="Pillai")
print(myMANOVA)
print("goodbye Greg...leaving R")
#q()